/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import model.Korisnik;
import model.Putovanje;
import model.Tip_prevoza;
import transfer.KorisnickiZahtjev;

/**
 *
 * @author s
 */
public class IzmeniPutovanje extends javax.swing.JDialog {
Putovanje putovanje;
private int id_putovanja;
    /**
     * Creates new form IzmeniPutovanje
     */
    public IzmeniPutovanje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }
     public IzmeniPutovanje(java.awt.Frame parent, boolean modal,Putovanje putovanje) {
        super(parent, modal);
        initComponents();
        this.putovanje=putovanje;
        this.id_putovanja=putovanje.getId();
        jTextFieldZemlja.setText(putovanje.getNazivDrzave());
        jTextArea1.setEnabled(false);
        jTextFieldDatumPolaska.setText(putovanje.getDatumPolaska().toString());
        jTextFieldDatumPovratka.setText(putovanje.getDatumPovratka().toString());
         kontroler.Kontroler.getInstance().setIzmeniPutovanje(this);
        popuniComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDatumPolaska = new javax.swing.JTextField();
        jTextFieldDatumPovratka = new javax.swing.JTextField();
        jTextFieldZemlja = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldDatumPolaska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatumPolaskaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel2.setText("Tip prevoznog sredstva");

        jLabel3.setText("Datum povratka u formatu \"yyyy-MM-dd\" :");

        jLabel4.setText("Datum polaska u formatu \"yyyy-MM-dd\" :");

        jButton1.setText("Izmeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Napisite zemlju/zemlje  iz Evropske Unije u koju zelite da idete(sisanom latinicom).\nNa primjer:\"Ceska\",\"Madjarska\",..");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 140, Short.MAX_VALUE)
                    .addComponent(jTextFieldDatumPovratka)
                    .addComponent(jTextFieldDatumPolaska)
                    .addComponent(jTextFieldZemlja))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldZemlja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatumPovratka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              LocalDate datumPolaska=null;
        LocalDate datumPovratka =null;  
        if(jTextFieldZemlja.getText().isEmpty() || jTextFieldDatumPolaska.getText().isEmpty() || jTextFieldDatumPovratka.getText().isEmpty()){
                                 JOptionPane.showMessageDialog(this, "Niste uneli drzavu/datumPovratka/datumPolaska", "Greska", JOptionPane.INFORMATION_MESSAGE);

             }
             else{
                 try {
                      datumPolaska=LocalDate.parse(jTextFieldDatumPolaska.getText());
             datumPovratka=LocalDate.parse(jTextFieldDatumPovratka.getText());
                 } catch (DateTimeParseException dtp) {
   JOptionPane.showMessageDialog(this, "Niste uneli fino datume", "Greska", JOptionPane.INFORMATION_MESSAGE);
                        jTextFieldDatumPolaska.setText("");
                        jTextFieldDatumPovratka.setText("");
                 }
        
//            List<String> drzave=new ArrayList<>();
            Korisnik korisnik=new Korisnik(null, null, null, null, null, null, null);
            Tip_prevoza tip_prevoz=(Tip_prevoza) jComboBox1.getSelectedItem();
            
            String drzava=jTextFieldZemlja.getText().toLowerCase();
//            drzave.add(drzava);
            Putovanje putovanjeZaizmenu=new Putovanje(id_putovanja,korisnik, drzava, tip_prevoz, LocalDate.now(), datumPolaska, datumPovratka,true);
            KorisnickiZahtjev kz=new KorisnickiZahtjev(putovanjeZaizmenu, operacija.Operacija.IZMENI);
            komunikacija.Komunikacija.getInstance().posaljiZahtjev(kz);
//            KorisnickiZahtjev kz=new KorisnickiZahtjev(putovanje, operacija.Operacija.PUTOVANJE);
//            komunikacija.Komunikacija.getInstance().posaljiZahtjev(kz);
          
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldDatumPolaskaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatumPolaskaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatumPolaskaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Tip_prevoza> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDatumPolaska;
    private javax.swing.JTextField jTextFieldDatumPovratka;
    private javax.swing.JTextField jTextFieldZemlja;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
       jComboBox1.addItem(Tip_prevoza.AUTO);
        jComboBox1.addItem(Tip_prevoza.AUTOBUS);
        jComboBox1.addItem(Tip_prevoza.AVION);
        jComboBox1.addItem(Tip_prevoza.BROD);
        jComboBox1.addItem(Tip_prevoza.MOTOCIKL);
        jComboBox1.addItem(Tip_prevoza.VOZ);
    }

    public void DatumPrije() {
          JOptionPane.showMessageDialog(this, "Uneseni datum je prije trenutnog", "Greska", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
    }
    public void predugoPutovanje() {
        JOptionPane.showMessageDialog(this, "Putovanje traje duze od 90 dana", "Greska", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
    }

    public void datumPolaskaPrijePovratka() {
       JOptionPane.showMessageDialog(this, "Datum polaska je prije datuma povratka", "Greska", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");    
    }

    public void uspesnoDodavanjePrijave() {
        JOptionPane.showMessageDialog(this, "Uspesno ste izmenili prijavu", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
}

    public void NijeClanica(String tojeTo2) {
           JOptionPane.showMessageDialog(this,tojeTo2.substring(0, 1).toUpperCase() + tojeTo2.substring(1).toLowerCase()+" Nije clanica EU!", "NEuspeh", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldZemlja.setText("");
    }

    public void PreklapajuSe(String tojeTo2) {
        JOptionPane.showMessageDialog(this, "Vec imate prijavu u tom vremenskom periodu za  putovanje u "+tojeTo2, "Uspeh", JOptionPane.INFORMATION_MESSAGE);
jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
        jTextFieldZemlja.setText("");
    }
}
