/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import model.Putovanje;
import transfer.KorisnickiZahtjev;

/**
 *
 * @author s
 */
public class PregledPutovanja extends javax.swing.JDialog {
    ModelTabelePutovanja mtp;
    java.awt.Frame parent;
    /**
     * Creates new form PregledPutovanja
     */
    public PregledPutovanja(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.parent=parent;
        kontroler.Kontroler.getInstance().setPregledPutovanja(this);
        Posalji();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Izmeni Putovanje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int red= jTable1.getSelectedRow();
        
        if(red==-1){
            JOptionPane.showMessageDialog(this, "selektujte neki red tabele", "Greska", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Putovanje putovanje=mtp.vratiRed(red);
            System.out.println("ovo je id putovanja");
            System.out.println(putovanje.getId());
             if(ChronoUnit.DAYS.between( LocalDate.now(),putovanje.getDatumPolaska())<=2){
             JOptionPane.showMessageDialog(parent, "Nazalost putovanje je zakljucano, ne mozete ga mijenjati", "Greska", JOptionPane.INFORMATION_MESSAGE);
         }else if(putovanje.getDatumPolaska().isBefore(LocalDate.now())){
             JOptionPane.showMessageDialog(parent, "Prijava je zavrsena!!", "Greska", JOptionPane.INFORMATION_MESSAGE);
         }else{
            IzmeniPutovanje izmeni=new IzmeniPutovanje(parent, true,putovanje);
            izmeni.setVisible(true);
}
             }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void Posalji() {
        KorisnickiZahtjev kz=new KorisnickiZahtjev(null,operacija.Operacija.POPUNITABELU);
        komunikacija.Komunikacija.getInstance().posaljiZahtjev(kz);
    }

    public void popuniTabelu(List<Putovanje> listaPutovanja) {
         mtp=new ModelTabelePutovanja(listaPutovanja);
        jTable1.setModel(mtp);
    }
}
