/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Korisnik;
import model.Putovanje;
import model.Tip_prevoza;
import transfer.KorisnickiZahtjev;

/**
 *
 * @author s
 */
public class PrijavaPutovanja extends javax.swing.JFrame {
String trenutna=null;
    /**
     * Creates new form PrijavaPutovanja
     */
    public PrijavaPutovanja(java.awt.Frame parent, boolean modal) {
        initComponents();
        popuniComboBox();
        kontroler.Kontroler.getInstance().setPf(this);
        jTextArea1.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDatumPolaska = new javax.swing.JTextField();
        jTextFieldDatumPovratka = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldZemlja = new javax.swing.JTextField();
        jButtonPosalji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldDatumPolaska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatumPolaskaActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum polaska u formatu \"yyyy-MM-dd\" :");

        jLabel2.setText("Datum povratka u formatu \"yyyy-MM-dd\":");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>()
        );

        jLabel3.setText("Izaberite tip prevoznog sredstva");

        jButtonPosalji.setText("Posalji Prijavu");
        jButtonPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Napisite zemlju/zemlje  iz Evropske Unije u koju zelite da idete(sisanom latinicom).\nNa primjer:\"Ceska\",\"Madjarska\",..");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonPosalji)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldZemlja, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDatumPolaska, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldDatumPovratka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldZemlja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDatumPovratka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButtonPosalji)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDatumPolaskaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatumPolaskaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatumPolaskaActionPerformed

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
       LocalDate datumPolaska=null;
        LocalDate datumPovratka =null;  
        if(jTextFieldZemlja.getText().isEmpty() || jTextFieldDatumPolaska.getText().isEmpty() || jTextFieldDatumPovratka.getText().isEmpty()){
                                 JOptionPane.showMessageDialog(this, "Niste uneli drzavu/datumPovratka/datumPolaska", "Greska", JOptionPane.INFORMATION_MESSAGE);

             }
             else{
                 try {
                      datumPolaska=LocalDate.parse(jTextFieldDatumPolaska.getText());
             datumPovratka=LocalDate.parse(jTextFieldDatumPovratka.getText());
                 } catch (DateTimeParseException dtp) {
   JOptionPane.showMessageDialog(this, "Niste uneli fino datume", "Greska", JOptionPane.INFORMATION_MESSAGE);
                        return;
                 }
        
//            List<String> drzave=new ArrayList<>();
            Korisnik korisnik=new Korisnik(null, null, null, null, null, null, null);
            Tip_prevoza tip_prevoz=(Tip_prevoza) jComboBox1.getSelectedItem();
            String drzava=jTextFieldZemlja.getText().toLowerCase();
            String[] drzave=drzava.split(",");
//            System.out.println(drzave[0]);
//            drzave.add(drzava);
          for(int i=0;i<drzave.length;i++){
              trenutna=drzave[i];
            Putovanje putovanje=new Putovanje(korisnik, drzave[i], tip_prevoz, LocalDate.now(), datumPolaska, datumPovratka,true);
            KorisnickiZahtjev kz=new KorisnickiZahtjev(putovanje, operacija.Operacija.PUTOVANJE);
            komunikacija.Komunikacija.getInstance().posaljiZahtjev(kz);
//            KorisnickiZahtjev kz=new KorisnickiZahtjev(putovanje, operacija.Operacija.PUTOVANJE);
//            komunikacija.Komunikacija.getInstance().posaljiZahtjev(kz);
             }
          
             }
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JComboBox<Tip_prevoza> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDatumPolaska;
    private javax.swing.JTextField jTextFieldDatumPovratka;
    private javax.swing.JTextField jTextFieldZemlja;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        jComboBox1.addItem(Tip_prevoza.AUTO);
        jComboBox1.addItem(Tip_prevoza.AUTOBUS);
        jComboBox1.addItem(Tip_prevoza.AVION);
        jComboBox1.addItem(Tip_prevoza.BROD);
        jComboBox1.addItem(Tip_prevoza.MOTOCIKL);
        jComboBox1.addItem(Tip_prevoza.VOZ);
    }

    public void DatumPrije(String tojeTo) {
        JOptionPane.showMessageDialog(this, "Uneseni datum je prije trenutnog", "Greska", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
    }

    public void predugoPutovanje(String tojeTo) {
        JOptionPane.showMessageDialog(this, "Putovanje traje duze od 90 dana za putovanje u "+tojeTo, "Greska", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
    }

    public void datumPolaskaPrijePovratka(String tojeTo) {
        JOptionPane.showMessageDialog(this, "Datum polaska je prije datuma povratka za putovanju u "+tojeTo, "Greska", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
    }

    public void uspesnoDodavanjePrijave(String tojeTo) {
JOptionPane.showMessageDialog(this, "Uspesno ste dodali prijavu za putovanje u "+tojeTo, "Uspeh", JOptionPane.INFORMATION_MESSAGE);
jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
        jTextFieldZemlja.setText("");

    }

    public void PreklapajuSe(String tojeTo) {
        JOptionPane.showMessageDialog(this, "Vec imate prijavu u tom vremenskom periodu za  putovanje u "+tojeTo, "Uspeh", JOptionPane.INFORMATION_MESSAGE);
jTextFieldDatumPolaska.setText("");
        jTextFieldDatumPovratka.setText("");
        jTextFieldZemlja.setText("");
    }

    public void NijeClanica(String tojeTo) {
             JOptionPane.showMessageDialog(this,tojeTo.substring(0, 1).toUpperCase() + tojeTo.substring(1).toLowerCase()+" Nije clanica EU!", "NEuspeh", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldZemlja.setText("");
    }
}
